### ISSUE TITLE
Error in Mounting a folder as volume within the docker

### ISSUE THREAD

**Issue by raamana** [BIDS-Apps/oppni#11]
Hi @chrisfilo 

I was able to build the docker, the CI is failing at this command below. I googled it a bit, and it doesn't seem to be about anything specific or clear. Any ideas?

Thanks.

```
Failing command: docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test1:/bids_dataset -v ${HOME}/outputs1:/outputs bids/${CIRCLE_PROJECT_REPONAME} /bids_dataset /outputs participant --participant_label 01 
Exit code: 127 
Output:
INFO[0000] Unable to locate /bids_dataset               

```

**Comment by chrisfilo** [comment]
Nothing comes to my mind immediately. Does it work locally? Did you try
debugging with ssh access on circle?

**Comment by raamana** [comment]
It does work locally on my mac, and also on a CentOs workstation.

I did try debugging via SSH - the few times I tried it was more trouble than worth: cache not loading properly, triggering a rebuild of docker etc. Moreover, I am not sure the mounting problem within a docker image can be debugged via ssh.

**Comment by raamana** [comment]
I figured it.

**Comment by chrisfilo** [comment]
what was it?

**Comment by raamana** [comment]
It was the missing entry point to the python wrapper! 

Everything ran fine, and OPPNI successfully processed the test1 dataset for the participant and group levels.

**Comment by chrisfilo** [comment]
Awesome!
