### ISSUE TITLE
OPPNI is hardcoded only to run on datasets with tasks named "linebisection"

### ISSUE THREAD

**Issue by chrisgorgo** [BIDS-Apps/oppni#16]
https://github.com/BIDS-Apps/oppni/blob/master/oppni.py#L187

**Comment by raamana** [comment]
That's a shame it still exists like that. This was supposed to be a quick start to test few datasets, while pybids and grabbids are ready. I will update it. I remember the task name will be supplied to the OPPNI wrapper with the argument --task_name, yes?

**Comment by chrisfilo** [comment]
I was not involved in writing the OPPNI wrapper - I do not know the answer to that question.

**Comment by raamana** [comment]
I guess my question was not clear. I was referring to how the BIDS app receive various info about the task to be run. Like --participant_label, do the BIDS app receive a --task_name argument when they are launched? If it's not supplied, we should of course try deduce it from the BIDS dataset itself.

**Comment by chrisfilo** [comment]
I see. This has not been standardized, but `--task_name` seems reasonable.

**Comment by raamana** [comment]
That's probably another reason why we might have tried to do something to get the testing moving.

Which python package do you recommend to query bids dataset info? It seems pybids is the one, there are links and [uncorrected] references to grabbids and others, that are confusing to me in the documentation.

**Comment by chrisfilo** [comment]
pybids is the only Python package for querying BIDS datasets I am aware of. Please [open an issue](https://github.com/INCF/pybids/issues) describing which aspect of the documentation you find confusing or even better open a pull request with suggested improvement.

**Comment by raamana** [comment]
Thanks for the clarification, that's what I had in mind. Just wanted to get started from the right package.
