### ISSUE TITLE
Installed bids-validator twice?

### ISSUE THREAD

**Issue by sajjadtorabian** [BIDS-Apps/oppni#18]
Hello,

Although the Dockerfile for oppni is written on top of base_afni (which is on top of base_validator that includes bids-validator installation) bids-validator is installed again. What is the reason for that? Is it because in base_validator, bids-validator version 0.21.1 is used, but we want to upgrade here and therefore install 0.21.2?

**Comment by raamana** [comment]
I think it was a matter of making it work back then. if you don't have a compelling reason to use the latest, I would use it as is.
