### ISSUE TITLE
Layers are getting big

### ISSUE THREAD

**Issue by chrisfilo** [BIDS-Apps/oppni#2]
Docker hub runs out of space whe nbuilding this container: https://hub.docker.com/r/bids/oppni/builds/bgtw9ydrvjue7b7p8gxskjf/

One way to improve this is by not storing the linux_openmp_64.tgz and MCR_R2012b_glnxa64_installer.zip files. Output of wget can be directly streamed to tar and unzip.

**Comment by raamana** [comment]
Thanks Chris for the pointers, I will optimize our docker file.

**Comment by raamana** [comment]
As the build is successful now and will be cached from now, can I ignore this optimization for now? We may experiment with different versions of MCR in the future, whence I can try to optimize in terms of disk space.

**Comment by chrisfilo** [comment]
Might be worth keeping this open as a low priority problem and revisit it
in the future (when we retire and have too much free time on our hands ;)

**Comment by raamana** [comment]
Sure.

**Comment by raamana** [comment]
Is this still a concern, Chris?

**Comment by chrisfilo** [comment]
nope

**Comment by raamana** [comment]
Thanks.
