### ISSUE TITLE
Docker Not Using Cache in Subsequent Builds

### ISSUE THREAD

**Issue by raamana** [BIDS-Apps/oppni#3]
It is somewhat strange why Docker is not using previous builds from the cache in the subsequent calls of circle CI.

Hey @chrisfilo , can you take a look at 
https://github.com/BIDS-Apps/oppni/blob/master/circle.yml#L20
and see if something needs to be changed to reduce the build times?

Thanks.

**Comment by chrisfilo** [comment]
Yeah - I noticed this as well recently. I'm not sure why is this happening: we are following their guidelines: https://circleci.com/docs/docker/#caching-docker-layers

**Comment by chrisfilo** [comment]
I see the problem: https://github.com/docker/docker/issues/20380 - it's the docker version. I'll try to downgrade it to 1.9 on bids/example and see if this fixes the problem.

**Comment by raamana** [comment]
Cool. Good to know we know the source of the problem.

I will wait for your heads up before rebuilding.

**Comment by raamana** [comment]
Hey @chrisfilo I don't think your changes fixed it. The latest build is still redoing everything: https://circleci.com/gh/BIDS-Apps/oppni/24

**Comment by chrisfilo** [comment]
I expect circle requires at least one successful test run for the cache to
be stored and passed to a new build. Currently oppni fails on other tests
(unrelated to docker build. You can try to disable them temporarily.

Downgrading to docker 1.8 did fix the caching issue in other repos (see
https://circleci.com/gh/BIDS-Apps/example/48)

**Comment by raamana** [comment]
I see. I will do so.

**Comment by chrisfilo** [comment]
Hey - it works! https://circleci.com/gh/BIDS-Apps/oppni/26

**Comment by raamana** [comment]
It did :). The funny thing is it didn't rebuild the docker image this time, which we were expecting it to do.

Thanks for the pointers to get the build here.
