### ISSUE TITLE
The pipeline is currently disabled in tests

### ISSUE THREAD

**Issue by chrisfilo** [BIDS-Apps/oppni#6]
See: https://github.com/BIDS-Apps/oppni/blob/master/oppni.py#L91. I'm sure this is a work in progress, but I want to open this issue for the sake of tracking progress. Please close it when the pipeline will be re-enabled in tests.

**Comment by raamana** [comment]
Hey Chris, yes, it is a work in progress. I am waiting for Nathan to make some changes to some of his components, to rerun the tests on the sample datasets. 

Also is there a chance we can have more sample datasets available for testing, in the same manner as done in our current CI? Thanks.

**Comment by chrisfilo** [comment]
I understand this is work in progress I only opened this issue to help me and other users see the status of the App. 

You can find more examples here: http://bids.neuroimaging.io/#examples as well as at openfmri.org (all recent datasets should be BIDS).

**Comment by raamana** [comment]
Tests are enabled now, and are being tested locally, before pushing to CircleCI.
